/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as HouseRouteImport } from './routes/house'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as TheFiveRouteImport } from './routes/the-five'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const TheFiveRoute = TheFiveRouteImport.update({
  id: '/the-five',
  path: '/the-five',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/businesses': typeof BusinessesRoute
  '/family': typeof FamilyRoute
  '/house': typeof HouseRoute
  '/library': typeof LibraryRoute
  '/manufacturing': typeof ManufacturingRoute
  '/plans': typeof PlansRoute
  '/portal': typeof PortalRoute
  '/programme': typeof ProgrammeRoute
  '/projects': typeof ProjectsRoute
  '/record': typeof RecordRoute
  '/sectors': typeof SectorsRoute
  '/the-five': typeof TheFiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/businesses': typeof BusinessesRoute
  '/family': typeof FamilyRoute
  '/house': typeof HouseRoute
  '/library': typeof LibraryRoute
  '/manufacturing': typeof ManufacturingRoute
  '/plans': typeof PlansRoute
  '/portal': typeof PortalRoute
  '/programme': typeof ProgrammeRoute
  '/projects': typeof ProjectsRoute
  '/record': typeof RecordRoute
  '/sectors': typeof SectorsRoute
  '/the-five': typeof TheFiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/businesses': typeof BusinessesRoute
  '/family': typeof FamilyRoute
  '/house': typeof HouseRoute
  '/library': typeof LibraryRoute
  '/manufacturing': typeof ManufacturingRoute
  '/plans': typeof PlansRoute
  '/portal': typeof PortalRoute
  '/programme': typeof ProgrammeRoute
  '/projects': typeof ProjectsRoute
  '/record': typeof RecordRoute
  '/sectors': typeof SectorsRoute
  '/the-five': typeof TheFiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/businesses'
    | '/family'
    | '/house'
    | '/library'
    | '/manufacturing'
    | '/plans'
    | '/portal'
    | '/programme'
    | '/projects'
    | '/record'
    | '/sectors'
    | '/the-five'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/businesses'
    | '/family'
    | '/house'
    | '/library'
    | '/manufacturing'
    | '/plans'
    | '/portal'
    | '/programme'
    | '/projects'
    | '/record'
    | '/sectors'
    | '/the-five'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/businesses'
    | '/family'
    | '/house'
    | '/library'
    | '/manufacturing'
    | '/plans'
    | '/portal'
    | '/programme'
    | '/projects'
    | '/record'
    | '/sectors'
    | '/the-five'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BusinessesRoute: typeof BusinessesRoute
  FamilyRoute: typeof FamilyRoute
  HouseRoute: typeof HouseRoute
  LibraryRoute: typeof LibraryRoute
  ManufacturingRoute: typeof ManufacturingRoute
  PlansRoute: typeof PlansRoute
  PortalRoute: typeof PortalRoute
  ProgrammeRoute: typeof ProgrammeRoute
  ProjectsRoute: typeof ProjectsRoute
  RecordRoute: typeof RecordRoute
  SectorsRoute: typeof SectorsRoute
  TheFiveRoute: typeof TheFiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-five': {
      id: '/the-five'
      path: '/the-five'
      fullPath: '/the-five'
      preLoaderRoute: typeof TheFiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BusinessesRoute: BusinessesRoute,
  FamilyRoute: FamilyRoute,
  HouseRoute: HouseRoute,
  LibraryRoute: LibraryRoute,
  ManufacturingRoute: ManufacturingRoute,
  PlansRoute: PlansRoute,
  PortalRoute: PortalRoute,
  ProgrammeRoute: ProgrammeRoute,
  ProjectsRoute: ProjectsRoute,
  RecordRoute: RecordRoute,
  SectorsRoute: SectorsRoute,
  TheFiveRoute: TheFiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
